language: php
php:
  - '7.1'
  - '7.2'

script:
  - composer install
  - vendor/bin/phpunit
  - vendor/bin/phpunit --coverage-clover=coverage.xml --whitelist=src/

after_success:
 - bash <(curl -s https://codecov.io/bash)
