ignore:
  - src/Controllers                                # Controllers dont have any logic
  - src/Repositories                               # Should be tested by integration tests
  - src/Generators                                 # Just clue code